### Why PyTorch?
- Easy to use
- Strong GPU support - models run fast
- Many algorithms are already implemented
- Automatic differentiation
- Similar to numpy

In [61]:
import torch
import torch.nn as nn

In [2]:
# Tensor in pytorch
x = torch.tensor([1,2,3])
print(x)

# Random Tensor
x = torch.randn((2, 2))
print("Tensor: ", x)
print("Shape: ", x.shape)
print("Dimension: ", x.dim())

tensor([1, 2, 3])
Tensor:  tensor([[-0.6909,  0.5419],
        [-2.1515, -0.7830]])
Shape:  torch.Size([2, 2])
Dimension:  2


In [3]:
# Matrix Multiplication
x = torch.tensor([[2,2],[1,1]])
y = torch.tensor([[1,2],[3,4]])
print(torch.matmul(x, y))

tensor([[ 8, 12],
        [ 4,  6]])


In [14]:
# Element-wise Multiplication
print(x * 2)

x = torch.tensor([2])
y = torch.tensor([10])
print(torch.matmul(x, y))
print((x * y)) # Same as matmul, needs unpacking through * operator

tensor([4])
tensor(20)
tensor([20])


In [5]:
# Zero, One and Identity tensors
a = torch.zeros((2,2))
print(a)
b = torch.ones((2,2))
print(b)
c = torch.eye((2))
print(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [16]:
# Forward Propagation: Intuition
# A(10,10)-----\
#               \ + U(10,10)____
# B(10, 10)-----/               \ matmul V (10,10)-----> Average W(1) 
#                               /
# C(10, 10)-------------------/

A = torch.rand(10, 10)
B = torch.rand(10, 10)
C = torch.rand(10, 10)

U = A + B
V = torch.matmul(U, C)

print(torch.mean(V))

tensor(5.1381)


### Derivative Example - Backward Pass

![](derivative.PNG)

In [23]:
# Backpropagation in PyTorch
# requires_grad=True tells pytorch that we need derivatives of respective tensor
A = torch.tensor(2., requires_grad=True)
B = torch.tensor(1., requires_grad=True)
C = torch.tensor(3., requires_grad=True)

U = A + B
V = U * C

# Compute the Derivatives
V.backward()

print("Forward U: {}".format(U))
print("Forward V: {}".format(V))

# Print the Gradients of the tensors
print("Gradient of A: {}".format(A.grad))
print("Gradient of B: {}".format(B.grad))
print("Gradient of C: {}".format(C.grad))

Forward U: 3.0
Forward V: 9.0
Gradient of A: 3.0
Gradient of B: 3.0
Gradient of C: 3.0


In [60]:
# Fully Connected NN
torch.manual_seed(0)
input_layer = torch.rand(10, requires_grad=True)

w1 = torch.rand(10, 20)
w2 = torch.rand(20, 20)
w3 = torch.rand(20, 1)
h1 = torch.matmul(input_layer, w1)
h2 = torch.matmul(h1, w2)
output_layer = torch.matmul(h2, w3)

output_layer.backward()

print(output_layer)
print(input_layer.grad)

tensor([227.7676], grad_fn=<SqueezeBackward3>)
tensor([46.7401, 44.6531, 60.3256, 50.8371, 46.1656, 43.8929, 54.2853, 36.6519,
        57.5263, 48.2738])


In [182]:
ip = torch.rand(784)
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

hidden_1 = torch.matmul(ip, weight_1)
op = torch.matmul(hidden_1, weight_2)

print(op/torch.mean(op))

tensor([0.9461, 0.9648, 0.9577, 0.9819, 1.0730, 1.0747, 0.9394, 1.0397, 1.0242,
        0.9985])


### Building a NN - PyTorch style

In [177]:
torch.manual_seed(0)
class NN(nn.Module):
    def __init__(self):
        super(NN, self).__init__()
        self.l1 = nn.Linear(10, 20)
        self.l2 = nn.Linear(20, 20)
        self.l3 = nn.Linear(20, 1)
        self.out = nn.Sigmoid()
        
    # Forward Pass
    def forward(self, x):
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.out(x)
        return x
    
# Instantiate NN class
input_layer = torch.rand(10, requires_grad=True)
net = NN()
result = net(input_layer)
print(result)

tensor([0.4428], grad_fn=<SigmoidBackward0>)
