In [1]:
import numpy as np

#### GOAL
- How to write clean, fast and efficient Python code
- How to profile your code for bottlenecks
- How to eliminate bottlenecks and bad design patterns

![](efficient_code.PNG)

- <a href='https://peps.python.org/pep-0020/'>The Zen of Python<a>

In [1]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

# Non-Pythonic approach of printing the list
i = 0
lst = []
while i < len(names):
    if len(names[i]) >= 6:
        lst.append(names[i])
    i += 1
print(lst)

['Kramer', 'Elaine', 'George', 'Newman']


In [5]:
# More Pythonic approach of printing the list
lst = []
for i in names:
    if len(i) >= 6:
        lst.append(i)
print(lst)

['Kramer', 'Elaine', 'George', 'Newman']


In [6]:
# Best Pythonic way
lst = [name for name in names if len(name) >= 6]
print(lst)

['Kramer', 'Elaine', 'George', 'Newman']


### Building with built-ins
- The Python Standard Library
<br>

![](builtin.PNG)

In [31]:
# range()
even_num = range(2, 11, 2)
print('range(): ', list(even_num))

# enumerate(): Create an indexed list of objects
letters = ['a', 'b', 'c', 'd']
index_letters = enumerate(letters)
print('enumerate(): ', list(index_letters))

# enumerate() with start index passed
st_letters = enumerate(letters, 10)
print('enumerate(letters, 10): ', list(st_letters))

# map(): Applies a function over an object
num = [10.5, 2.2, 6.8]
print('map(): ', list(map(round, num)))

# map() and lambda (anonymous function)
sqrd = map(round, list(map(lambda x: x ** 2, num)))
print('map() with lambda: ', list(sqrd))

# Unpacking with * operator
nums = range(0, 10, 2)
print(nums)
print([nums])
print('Unpacked: ', [*nums])

range():  [2, 4, 6, 8, 10]
enumerate():  [(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]
enumerate(letters, 10):  [(10, 'a'), (11, 'b'), (12, 'c'), (13, 'd')]
map():  [10, 2, 7]
map() with lambda:  [110, 5, 46]
range(0, 10, 2)
[range(0, 10, 2)]
Unpacked:  [0, 2, 4, 6, 8]


In [39]:
# Enumerate Practice
names = ['Pinkman', 'Rick', 'Walter', 'Morty']
name_index = []
for i, name in enumerate(names):
    x = (name, i)
    name_index.append(x)
print(name_index)

# Using List comprehension
name_index = [(i, name) for i, name in enumerate(names)]
print(name_index)

[('Pinkman', 0), ('Rick', 1), ('Walter', 2), ('Morty', 3)]
[(0, 'Pinkman'), (1, 'Rick'), (2, 'Walter'), (3, 'Morty')]


In [42]:
# Map practice
name_upper = map(str.upper, names)
print([*name_upper])

['PINKMAN', 'RICK', 'WALTER', 'MORTY']


In [69]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original Numbers: \n', nums)
print('Second Row of Number: ', nums[1,:])
print('Elements greater than 6: ', nums[nums > 6])
print('Double: \n', nums * 2)
nums[:,2] = nums[:,2] + 1
print('Replace 3rd Col or Numbers: \n', nums)

Original Numbers: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Second Row of Number:  [ 6  7  8  9 10]
Elements greater than 6:  [ 7  8  9 10]
Double: 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Replace 3rd Col or Numbers: 
 [[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


In [87]:
# Festivus Practice
times = [*range(10, 50, 10)]
np_times = np.array(times)
new_times = np_times - 3

guest_arrivals = [(names[i], time)for i, time in enumerate(new_times)]
def welcome(name_time):
    return ('Welcome {}, You are {} min late'.format(name_time[0], name_time[1]))

welcome_guests = map(welcome, guest_arrivals)
print(*[*welcome_guests], sep='\n')

Welcome Pinkman, You are 7 min late
Welcome Rick, You are 17 min late
Welcome Walter, You are 27 min late
Welcome Morty, You are 37 min late


### Examining runtime

#### Why time our code?
- Helps pick optimal coding approach
- Faster code == more efficient code

#### How to time our code?
- Magic commands: enhancements on top of normal python syntax
- prefixed by the '%' characters
- all commands at %lsmagic

#### %timeit: Specifying number of runs/loops
- Setting the # of runs (```-r```) and/or loops (```-n```)

#### Using %timeit in cell magic mode
- Cell magic (```%%timeit```)

#### Saving %timeit output
- Saving the output to a variable (```-o```)
- ```times = %timeit -o rand_nums = np.random.rand(1000)```
- All times: ```times.timings```
- Best time: ```times.best```
- Worst time: ```times.worst```

#### Reference table of time orders of magnitude
![](time_order_mag.PNG)

In [27]:
# Using %timeit
# %timeit nums = np.random.rand(1000)
%timeit -r2 -n10 nums = np.random.rand(1000)

56.8 µs ± 28.2 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


In [29]:
%%timeit
nums = []
for x in range(10):
    nums.append(x)

1.43 µs ± 540 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
times = %timeit -o nums = np.random.rand(1000)

11.4 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [40]:
times.timings, times.best, times.worst, times.average

([1.1526671999599785e-05,
  1.1297710000071675e-05,
  1.1509003000101074e-05,
  1.1388274000491946e-05,
  1.1569132999284192e-05,
  1.128898199996911e-05,
  1.148439300013706e-05],
 1.128898199996911e-05,
 1.1569132999284192e-05,
 1.1437738142807833e-05)

#### Formal name and Literal Syntax
<br>

![](form_lit_syn.PNG)

In [42]:
# Examining runtime of Python built-in data structures
t1 = %timeit -o l1 = list()
t2 = %timeit -o l2 = []

diff = (t1.average - t2.average) * (10**9)
print('Difference: {}'.format(diff)) # Literal syntax is faster

94 ns ± 9.25 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
51.9 ns ± 7.96 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
Difference: 42.07637571463627


In [44]:
%timeit num_list_com = [num for num in range(51)]
# print(num_list_com)

%timeit num_unpack = [*range(51)]
# print(num_unpack)

2.14 µs ± 95.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
522 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Reference: Datacamp